### ISSUE TITLE
Analyses Not Reproducible

### ISSUE THREAD

**Issue by DarioS** [rhong3/TCGA_melanoma#1]
The code has statements like `SAAV <- read_excel("Data/Melanoma proteome/MM List of peptides with SAAVs.xlsx")` which makes it not runnable by anyone other than the person who wrote the code. Fundamentally, the results of the project are not reproducible.
Recommended reading: [Ten Simple Rules for Reproducible Computational Research](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285), _PLoS Computational Biology_, 2013.

**Comment by rhong3** [comment]
Thanks for the comment! 
Please contact the lead authors of the paper for the original data files with the names in the code.
